In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
#execution performance 
size = 100_000_000

#python list 
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time : {end-start}")

#numpy array
np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2
end = time.time()
print(f"pnumpy array time : {end-start}")


python list time : 8.755784511566162
pnumpy array time : 0.19310903549194336


In [4]:
#memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_array.nbytes} bytes")


python list size = 80000005600000000 bytes
numpy array size = 800000000 bytes


In [5]:
#create - from lists
arr= np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2= np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [6]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d, arr2d.shape) #shape - dimensions (m*n)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [7]:
#create from scratch
arr1 = np.zeros((2,3), dtype ="int64") #prefill #typecasting 
print(arr1, arr1.shape)

arr3 = np.ones((5,), dtype ="int64")
print(arr3, arr3.shape)

arr4 = np.full((3,4), 100) #prefill with value
print(arr4, arr4.shape)

arr5 = np.eye(3) #identity matrix
print(arr5, arr5.shape)

arr6 = np.arange(0,11,2) #range elements (start, stop, step)
print(arr6, arr6.shape)

arr7 = np.linspace(1, 100, 3) #evenly spaced arrays
print(arr7, arr7.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [8]:
arr8 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr8.shape) #shape of the array
print(arr8.size) #total elements  - 9
print(arr8.dtype) #data type
print(arr8.ndim) #total number of dimensions

float_arr = arr8.astype(np.float64) #typecasting
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [9]:
#operations on array 

arr9 = np.array([[1,2,3],[4,5,6]])
print(arr9, arr9.shape)

reshaped = arr9.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr9.flatten() #2D array -> 1D array
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [10]:
#Indexing 
arr10 = np.array([1,2,3,4,5])
arr11 = np.array([[1,2,3],[4,5,6]])

print(arr10[0])
print(arr10[3])

print(arr11[1][2])
print(arr11[0][1])

1
4
6
2


In [11]:
#Fancy Indexing
arr12 = np.array([1,2,3,4,5])
idx = [0,1,3]
print(arr12[idx])

[1 2 4]


In [12]:
#Boolean Indexing
arr13 = np.array([1,2,3,4,5])
print(arr13[arr > 3])
print(arr[arr % 2 ==0])
print(arr[arr % 2 !=0])

[4 5]
[2 4]
[1 3 5]


In [13]:
#Slicing
arr14 = np.array([1,2,3,4,5])

print(arr[1:4]) #[start, end, stop]
print(arr[1:])
print(arr[:4])
print(arr[::4])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 5]


In [14]:
#data types 
arr15 = np.array([1,2,3,4,5])
print(arr15, arr15.dtype)

[1 2 3 4 5] int64


In [15]:
#multi-dimensional arrays
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis=0) #vertical addition
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis=1) #horizontal addition
print(sum_of_rows)

print(arr2d[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [16]:
#3D array 

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape)

#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:])
print(arr3D[:,:,0])

#arr3D[:,0,:] = 99 #replacing values with 99

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [17]:
#vectorization and broadcasting

#broadcasting 
arr16 = np.array([1,2,3,4,5])
arr17 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr16 + arr17)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [18]:
#normalize

arr18 = np.array([[1,2],[3,4]])

mean = (np.mean(arr18))
std = (np.std(arr18))

normalized_arr18 = (arr18 - mean)/std
print(normalized_arr18)

print(mean)
print(std)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
